services:
    _defaults:
        autoconfigure: true
        autowire: true

    Becklyn\Mimeo\:
        resource: '../../*'

    Becklyn\Mimeo\Copy\AssetsCopy:
        $projectDir: '%kernel.project_dir%'

    Becklyn\Mimeo\Finder\PackageFinder:
        $projectDir: '%kernel.project_dir%'
